import {
  BoldIcon,
  ItalicIcon,
  LinkIcon,
  SaveIcon,
  CodeIcon,
  AlignLeftIcon,
  PhotoIcon,
  AlignCenterIcon,
  AlignRightIcon,
  ParagraphIcon,
  HeadingH1Icon,
  HeadingH2Icon,
  HeadingH3Icon,
  HeadingH4Icon,
  HeadingH5Icon,
  HeadingH6Icon,
  QuoteIcon,
  HeadingIcon,
  TrashIcon,
} from "@/lib/icons";
import { ToolbarButton } from "./types";

const userAgent = globalThis?.navigator?.userAgent;
const isMac = userAgent?.indexOf("Mac") !== -1;

export const TOOLBAR_BUTTONS: ToolbarButton[] = [
  {
    sort: 0,
    id: "texts",
    icon: <BoldIcon />,
    alt: "Textos",
  },
  {
    sort: 0,
    id: "bold",
    icon: <BoldIcon />,
    alt: "Negrita",
    shortcut: `${isMac ? "⌘" : "Ctrl"}B`,
    parent: "texts",
  },
  {
    sort: 1,
    id: "italic",
    icon: <ItalicIcon />,
    alt: "Cursiva",
    shortcut: `${isMac ? "⌘" : "Ctrl"}I`,
    parent: "texts",
  },
  {
    sort: 1,
    id: "texts-types",
    icon: <HeadingIcon />,
    alt: "Tipos de texto",
  },
  {
    sort: 0,
    id: "paragraph",
    icon: <ParagraphIcon />,
    alt: "Párrafo",
    parent: "texts-types",
  },
  {
    sort: 1,
    id: "h1",
    icon: <HeadingH1Icon />,
    alt: "H1",
    parent: "texts-types",
  },
  {
    sort: 2,
    id: "h2",
    icon: <HeadingH2Icon />,
    alt: "H2",
    parent: "texts-types",
  },
  {
    sort: 3,
    id: "h3",
    icon: <HeadingH3Icon />,
    alt: "H3",
    parent: "texts-types",
  },
  {
    sort: 4,
    id: "h4",
    icon: <HeadingH4Icon />,
    alt: "H4",
    parent: "texts-types",
  },
  {
    sort: 5,
    id: "h5",
    icon: <HeadingH5Icon />,
    alt: "H5",
    parent: "texts-types",
  },
  {
    sort: 6,
    id: "h6",
    icon: <HeadingH6Icon />,
    alt: "H6",
    parent: "texts-types",
  },
  {
    sort: 7,
    id: "quote",
    icon: <QuoteIcon />,
    alt: "Cita",
    parent: "texts-types",
  },
  {
    sort: 2,
    id: "aligns",
    icon: <AlignLeftIcon />,
    alt: "Alineación",
  },
  {
    sort: 0,
    id: "align-left",
    icon: <AlignLeftIcon />,
    alt: "Alineación izquierda",
    shortcut: `${isMac ? "⌘" : "Ctrl"}L`,
    parent: "aligns",
  },
  {
    sort: 1,
    id: "align-center",
    icon: <AlignCenterIcon />,
    alt: "Alineación centrada",
    shortcut: `${isMac ? "⌘" : "Ctrl"}E`,
    parent: "aligns",
  },
  {
    sort: 2,
    id: "align-right",
    icon: <AlignRightIcon />,
    alt: "Alineación derecha",
    shortcut: `${isMac ? "⌘" : "Ctrl"}R`,
    parent: "aligns",
  },
  {
    sort: 3,
    id: "link",
    icon: <LinkIcon />,
    alt: "Enlace",
    shortcut: `${isMac ? "⌘" : "Ctrl"}K`,
  },
  {
    sort: 4,
    id: "photo",
    icon: <PhotoIcon />,
    alt: "Imagen",
    shortcut: `${isMac ? "⌘" : "Ctrl"}K`,
  },
  {
    sort: 5,
    id: "code",
    icon: <CodeIcon />,
    alt: "Bloque de código",
    shortcut: `${isMac ? "⌘" : "Ctrl"}H`,
  },
  {
    sort: 6,
    id: "save",
    icon: <SaveIcon />,
    alt: "Guardar",
    shortcut: `${isMac ? "⌘" : "Ctrl"}S`,
  },
  {
    sort: 7,
    id: "delete",
    icon: <TrashIcon />,
    alt: "Eliminar bloque",
    shortcut: `${isMac ? "⌘" : "Ctrl"}D`,
  }
];